# Probability
## Foundations of Machine Learning
## `! git clone https://www.github.com/DS3001/probability`

## Probability
- So we have some skills to get data and put into a workable form (data wrangling, EDA, visualization)
- We have some basic but powerful tools to analyze data and create predictive models ($k$NN, $k$MC, linear models, decision trees)
- We want to ask questions like, How much uncertainty does there appear to be in our predictions? How well is this model likely to perform on new data? Does this model work well in any absolute sense?
- To proceed, we need to add some more ideas about probability and randomness, in order to communicate with each other and understand tools
- These two lectures (probability and bootstrapping) are probably the most difficult in the class, but the payoff is absolutely worth it

## A Fair Die
- Let's consider something very simple: Rolling a "fair" 6-sided die where each side is equally likely.
- There are six sides with pips $\cdot$, $2\cdot$, $3\cdot$, $4\cdot$, $5\cdot$, and $6 \cdot$
- Besides the sides themselves, we can define outcomes like *odd*, $\left\lbrace 1\cdot, 3\cdot, 5\cdot \right\rbrace$, and *even*, $\left\lbrace 2\cdot, 4\cdot, 6\cdot \right\rbrace$.
- If each side is equally likely, the probability we observe any given side should be 1/6; this allows us to work out the likelihood of observing any particular collection of sides, like even or odd.
- What are all these ideas, in an abstract sense??

## A Fair Die
- There are six sides with pips $\cdot$, $2\cdot$, $3\cdot$, $4\cdot$, $5\cdot$, and $6\cdot$. **This is called the *sample space* and each possibility in it is called an outcome**.
- Besides the sides themselves, we can define outcomes like *odd*, $\left\lbrace 1\cdot, 3\cdot, 5\cdot \right\rbrace$, and *even*, $\left\lbrace 2\cdot, 4\cdot, 6\cdot \right\rbrace$. **This is called the set of *events*: all of the "relevant" sets of outcomes that might occur.**
- If each side is equally likely, the probability we observe any given side should be 1/6; this allows us to work out the likelihood of observing any particular collection of sides, like even or odd. **This is called a *probability function*, associating every event with a number between 0 and 1.**

## Probabilities
- There are many nuances about what rules a "probability function" must satisfy that we are going to gloss over
- The key rules are these:
  - The probability of nothing happening is zero, the probability of something happening is 1
  - The probability of every event is between zero and 1
  - If you have a set of events $e_1, e_2, ..., e_N$ where no outcome occurs in more than one event (e.g. even and odd), then
  $$
  p(e_1 \text{ and } e_2 \text{ and } ... \text{ and } e_n) = p(e_1) + p(e_2) + ... + p(e_N)
  $$
- Everything we talk about today holds for situations where there are a finite or infinite number of outcomes, as long as you set things up "correctly"

## Notation
- Let's call the sample space $S$ and individual outcomes $x$
- Let's call the set of all events $E$ and an individual event $e$
- Let's call the probability function $p(e)$
- We can write that $p(S)=1$, $0 \le p(e) \le 1$ for all events $e$ in $E$, and if every outcome appears at most once in a set of events $e_1, ..., e_n$, $p(e_1 \text{ and } e_2 \text{ and } ... \text{ and }e_n) = \sum_{i=1}^n p(e_i)$.

## Betting on Dice
- For example, let's bet on the roll of two six-sided die
- An outcome is a pair of die faces, like $(3\cdot,6\cdot)$. The sample space is:
$$
\left[ \begin{array}{cccccc}
(1\cdot,1\cdot) & (1\cdot,2\cdot) & (1\cdot,3\cdot) & (1\cdot,4\cdot) & (1\cdot,5\cdot) & (1\cdot,6\cdot) \\
(2\cdot,1\cdot) & (2\cdot,2\cdot) & (2\cdot,3\cdot) & (2\cdot,4\cdot) & (2\cdot,5\cdot) & (2\cdot,6\cdot) \\
(3\cdot,1\cdot) & (3\cdot,2\cdot) & (3\cdot,3\cdot) & (3\cdot,4\cdot) & (3\cdot,5\cdot) & (3\cdot,6\cdot) \\
(4\cdot,1\cdot) & (4\cdot,2\cdot) & (4\cdot,3\cdot) & (4\cdot,4\cdot) & (4\cdot,5\cdot) & (4\cdot,6\cdot) \\
(5\cdot,1\cdot) & (5\cdot,2\cdot) & (5\cdot,3\cdot) & (5\cdot,4\cdot) & (5\cdot,5\cdot) & (5\cdot,6\cdot) \\
(6\cdot,1\cdot) & (6\cdot,2\cdot) & (6\cdot,3\cdot) & (6\cdot,4\cdot) & (6\cdot,5\cdot) & (6\cdot,6\cdot)
\end{array} \right]
$$
- The events $E$ are all of the subsets of the above matrix (e.g. "All rolls where both results are even", "all rolls that sum to 7", "All rolls where both the dice show the same outcome")
- For fair dice, each pair above is equally likely with probabilty $1/36$
- Notice, the outcomes here aren't strictly numeric: They could be colors, animals, job titles, car models, anything. Outcomes aren't fundamentally numeric.

## Random Variables
- A **random variable** is a rule that assigns numbers to outcomes
- A random variable is a function $R$ that assigns a number $R(x)$ to each outcome $x$ in $S$
- A random variable is how we quantify the consequences of an uncertain phenomenon

## The Expectation
- What value is a random variable going to take?
- Since a random variable is a rule that assigns a numeric value to every outcome, we can weight those values by the probabilities they occur, and sum:
$$
\mathbb{E}[R] = p(x_1) R(x_1) + p(x_2)R(x_2) + ... + p(x_N)R(x_N) = \sum_{i =1}^N p(x_i)R(x_i)
$$
- If the outcomes are numbers and all equally likely, we can set $R(x_i) = x_i$ and $p(x_i) = 1/N$, which gives
$$
\mathbb{E}[R] = \dfrac{1}{N} x_1 + \dfrac{1}{N} x_2 + ... + \dfrac{1}{N} x_N = \dfrac{1}{N} \sum_{i =1}^N x_i
$$
- This is called the **expectation of $R$** or the **expected value of $R$**. It is often denoted by $\mu$ or $\mu_R$, to emphasize it's a theoretical/population value.

## Gambling
- What's the expected value of rolling two dice, if you get the sum of the faces in money?
- What's the expected value of a gamble where you get $\$10$ if the sum is strictly greater than 7, but $\$0$ if the sum is weakly less than 7?
- What's the expected value of a gamble where you get $\$$100 if the sum is odd? Even?
- What would you will be willing to pay for the above gambles?

## The Variance
- The **variance of $R$** is
$$\mathbb{V}[R] = p(x_1)(R(x_1)-\mathbb{E}[R])^2 + p(x_2)(R(x_2)-\mathbb{E}[V])^2 +
... + p(x_N)(R(x_N)-\mathbb{E}[R])^2 = \sum_{i=1}^N p(x_i)(R(x_i)-\mathbb{E}[R])^2
$$
- You can also write this as
$$
\mathbb{V}[R] = \mathbb{E}\left[ (R-\mathbb{E}[R])^2\right]= \mathbb{E}\left[ (R-\mu_R)^2\right]
$$
- The variance is often denoted $\sigma^2$ or $\sigma_R^2$, to emphasize it's a theoretical/population value.

## Random Number Generation in Python
- Suppose you have a set $S$, like $S = \{1,2,3,4,5,6\}$, or `S = np.arange(6)+1`. For example, suppose you want to sample observations from your data frame: that corresponds to `np.arange( df.shape[0])`.
    - To **sample with replacement**, you can use Numpy's `random.choice(S,size=n)` function to take $n$ draws from $S$, with the potential for repetition
    - To **sample without replacement**, you can use Numpy's `np.random.shuffle(S)` function to randomize the order of the elements in $S$, and then $S[:N]$ to slice the first $N$ elements from the shuffled $S$
- To draw `N` numbers from between 0 and 1 with uniform probability, you can use `np.random.uniform(size=N)`
- To draw `N` numbers from a normal distribution with mean $m$ and standard deviation $s$, you can use `np.random.normal(m,s,size=N)`

In [ ]:
import numpy as np
S = np.array([1,2,3,4,5,6]) # Object to sample
x = np.random.choice(S, size=3)
print(x)
x = np.random.choice(S, size=10)
print(x)

[5 1 2]
[1 1 3 4 3 1 4 4 3 3]


In [ ]:
S = np.array([1,2,3,4,5,6]) # Object to sample
N = 3 # Elements to take

np.random.shuffle(S) # 1. Shuffle x
print(S)
y = S[:N] # 2. Take the first N elements
print(y)

[6 1 3 4 5 2]
[6 1 3]


In [ ]:
np.random.uniform(size=10) # A random sample of uniformly distributed numbers

array([2.77220188e-01, 2.09544120e-01, 1.30356424e-02, 1.92719556e-01,
       5.99456346e-01, 9.62899767e-01, 4.34549892e-04, 7.49748596e-02,
       7.09421198e-02, 4.31349831e-01])

In [ ]:
np.random.normal(10,5,size=10) # A random sample of normally distributed numbers

array([17.86566832, 13.68901458,  6.96449255, 13.42888148,  9.45935987,
       16.79135465,  2.6811557 ,  6.66369038, 16.44308665, 17.78716328])

## Gambling
- What's the variance of rolling two dice and summing?
- What's the variance of a gamble where you get $\$10$ if the sum is strictly greater than 7, but $\$0$ if the sum is weakly less than 7?
- What's the variance of a gamble where you get $\$100$ if the sum is odd? Even?

## The Law of Large Numbers
- The next five slides are about expanding your understanding of the fundamental nature of reality
- If you are the kind of person who says they "do not like math" or "are not good at math", that's OK, this isn't on a test
- This is what real, useful mathematics looks like: A sequence of logical inferences which come together in a powerful insight about quantitative reality
- Even if you don't understand every line and manipulation, knowing roughly how humans create quantitative ideas and statistical evidence means your understanding of what is possible expands, and that is valuable on its own

## Markov's Inequality
- Suppose that $R(x_i) \ge 0$, so all the random variable only takes non-negative values
- Pick a value $a$ that is between $x_1$ and $x_N$. What can we say about the relationship between $p$, $\mathbb{E}[R]$, and $a$?
\begin{eqnarray*}
\mathbb{E}[R] &=& \sum_{R(x_i) < a} p(x_i) R(x_i) + \sum_{R(x_i) \ge a} p(x_i) R(x_i) \\
& \ge & \sum_{R(x_i) < a} p(x_i) 0 + \sum_{R(x_i) \ge a} p(x_i) R(x_i) \\
& \ge & \sum_{R(x_i) \ge a} p(x_i) a \\
& =& p[R \ge a] a
\end{eqnarray*}
- This implies that if $R(x) \ge 0$ for all $x$ in $S$, then for any $a$,
$$
p[R \ge a] \le \dfrac{\mathbb{E}[R]}{a}
$$
- This is called **Markov's Inequality**: The probability that a non-negative random variable exceeds a threshold (a) is bounded by its expectation divided by the threshold

- everything above a, we round down to a. everything below a gets rounded down to 0

## Chebyshev's Inequality
- OK, can we relate $\mathbb{E}[R]$, $p$, and $\sigma$ in a useful way?
- If we use Markov's inequality with $R(x) = (x-\mu)^2$, we get another useful inequality:
\begin{eqnarray*}
p[ |x-\mu| \ge d ] &=& p[ (x-\mu)^2 \ge d^2 ] \\
&\le& \dfrac{\mathbb{E}[ (X-\mu)^2 ]}{d^2 }\\
p[ |x-\mu| \ge d  ] &\le & \dfrac{\sigma^2}{d^2 }\\
\end{eqnarray*}
- This provides a bound on how far a random variable $R(x)=x$ can be from its average, based on the variance $\sigma^2$ and a distance $d$:
$$
p\left[ |x-\mu| \ge d \right] \le \dfrac{\sigma^2}{d^2}
$$
- This is called **Chebyshev's Inequality**: The distance $d$ a random variable $X$ is from its mean $\mu$ is bounded by its variance $\sigma^2$ divided by the distance squared $d^2$.

## Independent and Identically Distributed Sequences (iid)
- A fundamental concept in probability and statistics is the abstract idea of running an "experiment" over and over, and computing statistics for the results
- Let $x_1$ be the result of the first experiment, $x_2$ the result of the second, and so on
- Assume that the draws $x_1, x_2, ...$
  - are **identically distributed**: They are all drawn from the same distribution function and all have the same mean $\mu$ and variance $\sigma^2$
  - are **independent**: The outcome of draw $x_n$ doesn't affect the outcome of any draw $x_m$, $m \neq n$
- The **sample average** of our experimental sequence is
$$
\bar{X}_n = \dfrac{1}{N} \sum_{i=1}^n x_i
$$
and the **sample variance** of our experimental sequence is
$$
\bar{s}_n^2 = \dfrac{1}{N} \sum_{i=1}^n (x_i - \bar{X}_n)^2
$$

## Independent and Identically Distributed Sequences (iid)
- The sample average and sample variance are now, themselves, random variables, with their own outcomes, events, probabilities, and so on
- What is the expected value of $\bar{X}_n$?
$$
\mathbb{E}[\bar{X}_n] = \mathbb{E}\left[ \dfrac{1}{n}(x_1 + ... + x_n)\right] = \dfrac{\mathbb{E}[x_1] + ... + \mathbb{E}[x_n]}{n} =
\dfrac{\mu + ... + \mu}{n} = \dfrac{n\mu}{n} = \mu
$$
- Likewise (but slightly different steps)
$$
\mathbb{V}[\bar{X}_n] = \dfrac{\sigma^2}{n}
$$
- To emphasize that the sample space of $S_n$ depends on the sequence $n$, we'll write the probability function as $p_n$

## Law of Large Numbers
- Take the random variable as the sample mean $X_n$ of a sequence of iid random variables, with mean $\bar{X}_n = \dfrac{1}{n} \sum_{t=1}^n x_i$ and variance $\mathbb{V}[\bar{X}_n] = \sigma^2/n$
- By Chebyshev's inequality,
$$
p_n\left[ |\bar{X}_n - \mu|  \ge d \right] \le \dfrac{\mathbb{V}[\bar{X}_n]}{d^2} = \dfrac{\sigma^2}{n d^2}.
$$
- **As $n$ gets large on the far right, $\frac{\sigma^2}{nd^2}$ goes to zero, for any $d$.**
- The importance of this idea cannot be understated: This is one of the most important ideas that humanity has discovered
- This is called the **Law of Large Numbers**: Sample averages *converge in probability* to the true average $\mu$ as long as the variance $\sigma^2$ is finite.

## Example: Estimating Probabilities
- R is going to draw a number $h$ between 0 and 1, but it isn't going to tell us what it is. R will, however, flip a coin that comes up heads[1] with probability $h$ or tails[0] with probability $1-h$
- Each flip $x_i$ is either equal to 0 for tails or 1 for heads, so the average of the flips is
$$
\bar{X}_n = \dfrac{x_1+x_2 + ... + x_n}{n} = \{\text{The sample proportion of heads}\} = h_n
$$
- As the number of flips gets large, by the LLN, the sample average $h_n$ will converge in probability to the true value $h$
- As a consequence of the LLN, *sample proportions converge to population probabilities as the sample gets large*

In [ ]:
# Data generation:
h = np.random.uniform() # Unfair coin we don't observe
n = 100 # Sample Size
flips =  np.random.uniform(size=n) < h  # Flips we observe

# Our analysis of the data, 'flips':
h_n = flips.mean() # Our estimate of h
print(h_n)

# What's the true value?
print(h) # True value


0.3
0.36252279833801393


## Example: Estimating Averages
- Any given outcome of a gamble is not informative of the value of the gamble in expectation
- But if we average many iid plays of the gamble and average the payoffs, the LLN tells us that the sample average will converge to the true value of the gamble
- The expected value calculations we were doing earlier by hand can be done by simulation on a computer
- This is all mathematical finance/engineering is: More complex versions of this kind of calculation

In [ ]:
# Set up the gamble:
winning_values = np.array([7,11]) # Which values between 2 and 12 count as a 'win'?
winning_amount = 1 # Amount received if you win
losing_amount = 0 # Amount paid if you lose
die = np.arange(6)+1
n = 1000 # Number of simulations of the gamble

# Simulate the gamble:
rolls = np.random.choice(die, size=[n,2])  # Roll 2 dice n times
sums = rolls.sum(axis=1)

# Determine winning and losing rolls:
winning_rolls = np.in1d(sums,winning_values)
losing_rolls = 1-winning_rolls

# Compute payoffs:
payoff = winning_rolls*winning_amount + losing_rolls*losing_amount

# Compute expected payoff:
payoff.mean()

0.23

## Example: Regression
- How do we know regression means anything?
- The optimal coefficients in a simple linear regression $\hat{y}_i = a + b x_i$ can be written
\begin{eqnarray*}
a^*_N &=& \dfrac{1}{N} \sum_{i=1}^N y_i \\
b^*_N &=& \dfrac{ \frac{1}{N} \sum_{i=1}^N (y_i - \bar{y}_n)(x_i-\bar{x}_n)}{\frac{1}{N} \sum_{i=1}^N (x_i- \bar{x}_n)^2}
\end{eqnarray*}
- These are all just sample averages of various kinds. There are rules about how the LLN can be combined with these kinds of functions to know that $a^*_N$ and $b^*_N$ converge since $\bar{y}_N$ and $\bar{x}_N$ converge (Slutsky's Theorem, Portmanteau Theorem, Continuous Mapping Theorem).
- As the sample size gets large, there are theoretical limit values they converge to: We should expect order to arise out of the randomness, even if we have no idea what they are.

In [ ]:
import pandas as pd

n = 250 # Number of observations

## Data creation:
b0 = 1 # True intercept coefficient
b1 = 3 # True slope coefficient
b2 = 5 # True slope coefficient
x1 = np.random.normal(5,2,n) # Covariate 1
x2 = np.random.normal(-3,1,n) # Covariate 2
noise = np.random.normal(0,1,n) # Error term
y = b0 + b1*x1 + b2*x2 + noise # Compute Outcome/Target Variable
df = pd.DataFrame({'y':y,'x1':x1,'x2':x2}) # Create data frame

## Data analysis:
from sklearn.linear_model import LinearRegression # Import linear regression model
X = df.loc[:,['x1','x2']] # Construct data matrix
y = df['y'] # Response variable
reg = LinearRegression().fit(X, y) # Fit the linear model
print(reg.intercept_) # Intercept value
print(reg.coef_) # Regression coefficients


1.3389562512450843
[2.99058257 5.0926713 ]


## Next Class
- We have just admitted that our estimates (the $h_n$, the regression coefficients, etc.) are noisy: They'll be close to the truth if $N$ is large, by the Law of Large Numbers... but we know they're still not *exactly* correct
- Can we quantify this uncertainty about our estimates? How?
- This is going to motivate a framework called *bootstrapping*